[WORKER FATAL ERROR] Cannot save file into a non-existent directory: 'data/leonardo/2025-10-07_10-50-19-512985'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mmarcel3/crab/src/crab/cli/orchestrator.py", line 67, in run_from_cli
    engine.run(
  File "/leonardo/home/userexternal/mmarcel3/crab/src/crab/core/engine.py", line 240, in run
    self._run_worker(config, environment, output_dir)
  File "/leonardo/home/userexternal/mmarcel3/crab/src/crab/core/engine.py", line 523, in _run_worker
    log_data(out_format, os.path.join(data_directory, 'data'), data_container_list)
  File "/leonardo/home/userexternal/mmarcel3/crab/src/crab/core/engine.py", line 211, in log_data
    dataframe.to_csv(file_name, index=False)
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 3986, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/leonardo/home/userexternal/mmarcel3/crab/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data/leonardo/2025-10-07_10-50-19-512985'
